/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmPrincipalAdmin.java
 *
 * Created on 06/09/2011, 06:00:04 PM
 */
package gui;

import com.AreaCOM;
import com.UsuarioCOM;
import entidades.Area;
import entidades.Usuario;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.event.*;
import java.text.SimpleDateFormat;
import java.util.Date; 
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author Toditos
 */
public class frmPrincipalAdmin extends javax.swing.JFrame {

    private Usuario objUsuarioAdmin = new Usuario();
     private UsuarioCOM objUsuarioCOM=new UsuarioCOM();
      private Timer tiempo;
    private Date fecha;
    private Calendar reloj;
    private SimpleDateFormat formato;
    /** Creates new form frmPrincipalAdmin */
    public frmPrincipalAdmin(Usuario objUsuario) {
        initComponents();
        this.objUsuarioAdmin = objUsuario;
        this.setIconImage (new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage()); 
          setLocationRelativeTo(null);
          cargarDatos();
          cargarRegloj();
    }
    
      public void cargarRegloj()
    {
         formato = new SimpleDateFormat("dd/MM/yyyy");
        tiempo = new Timer(1000, new ActionListener(){
            
            public void actionPerformed(ActionEvent evt){
                fecha = new Date();
                lblFecha.setText(formato.format(fecha));
                
                reloj = Calendar.getInstance();
                lblHora.setText(reloj.get(Calendar.HOUR) + ":" +
                        reloj.get(Calendar.MINUTE) + ":" +
                        reloj.get(Calendar.SECOND) + " " +
                        ((reloj.get(Calendar.AM_PM) == 0) ? "am": "pm")); //if am o pm
            }
        });
        tiempo.start();
    }
    

     public void cargarDatos()
    {
        if(objUsuarioAdmin.getInt_nivel()==1)
        lblUsuario.setText("Administrador "+objUsuarioAdmin.getStr_nombre()+" "+objUsuarioAdmin.getStr_apellido());
        else
              lblUsuario.setText("Usuario "+objUsuarioAdmin.getStr_nombre()+" "+objUsuarioAdmin.getStr_apellido());
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnCPU1 = new javax.swing.JButton();
        btnCPU = new javax.swing.JButton();
        btnCPU2 = new javax.swing.JButton();
        btnCPU3 = new javax.swing.JButton();
        btnCPU4 = new javax.swing.JButton();
        btnCPU5 = new javax.swing.JButton();
        btnCPU6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        panel = new javax.swing.JPanel();
        Panel = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();
        lblCClave = new javax.swing.JLabel();
        Pcambiar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCActual = new javax.swing.JPasswordField();
        txtNClave = new javax.swing.JPasswordField();
        txtRClave = new javax.swing.JPasswordField();
        btn_CClave = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_Cancelar = new javax.swing.JButton();
        lblFecha = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        javax.swing.JMenuItem jmi_Empleado = new javax.swing.JMenuItem();
        jmt_Software = new javax.swing.JMenuItem();
        jmi_Cargo = new javax.swing.JMenuItem();
        jmt_Are = new javax.swing.JMenuItem();
        jmt_Departamento = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmi_Modelo = new javax.swing.JMenuItem();
        jmt_Marca = new javax.swing.JMenuItem();
        jmt_Tipo = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jmi_Accesorios = new javax.swing.JMenuItem();
        jmi_CPU = new javax.swing.JMenuItem();
        jmi_Monitor = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jmi_Componentes = new javax.swing.JMenuItem();
        jmi_Partes = new javax.swing.JMenuItem();
        jmi_Portatil = new javax.swing.JMenuItem();
        jmi_Impresora = new javax.swing.JMenuItem();
        jmi_Externo = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jmi_Proveedor = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jmi_Usuario = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Formulario Principal");
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mantenimiento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        btnCPU1.setFont(new java.awt.Font("Arial", 1, 14));
        btnCPU1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn_computador.png"))); // NOI18N
        btnCPU1.setText("Computadora");
        btnCPU1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCPU1ActionPerformed(evt);
            }
        });

        btnCPU.setFont(new java.awt.Font("Arial", 1, 14));
        btnCPU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn_cpu.png"))); // NOI18N
        btnCPU.setText("Modificar CPU");
        btnCPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCPUActionPerformed(evt);
            }
        });

        btnCPU2.setFont(new java.awt.Font("Arial", 1, 14));
        btnCPU2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn_portatil.png"))); // NOI18N
        btnCPU2.setText("Portatiles");
        btnCPU2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCPU2ActionPerformed(evt);
            }
        });

        btnCPU3.setFont(new java.awt.Font("Arial", 1, 14));
        btnCPU3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn_impresora.png"))); // NOI18N
        btnCPU3.setText("Impresoras");
        btnCPU3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCPU3ActionPerformed(evt);
            }
        });

        btnCPU4.setFont(new java.awt.Font("Arial", 1, 14));
        btnCPU4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn_equipos.png"))); // NOI18N
        btnCPU4.setText("Equipos");
        btnCPU4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCPU4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCPU1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(btnCPU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCPU4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(btnCPU3, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(btnCPU2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnCPU1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btnCPU2)
                .addGap(18, 18, 18)
                .addComponent(btnCPU3)
                .addGap(18, 18, 18)
                .addComponent(btnCPU4)
                .addGap(27, 27, 27)
                .addComponent(btnCPU)
                .addContainerGap())
        );

        btnCPU5.setFont(new java.awt.Font("Arial", 1, 14));
        btnCPU5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/orden.png"))); // NOI18N
        btnCPU5.setText("Ingresar Orden de Compra");
        btnCPU5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCPU5ActionPerformed(evt);
            }
        });

        btnCPU6.setFont(new java.awt.Font("Arial", 1, 14));
        btnCPU6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn_equipos.png"))); // NOI18N
        btnCPU6.setText("Compoentes Inhabilitados");
        btnCPU6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCPU6ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        btnSalir.setFont(new java.awt.Font("Arial", 1, 14));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn_salir.png"))); // NOI18N
        btnSalir.setText("Salir del Sistema");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lblUsuario.setFont(new java.awt.Font("Arial", 1, 14));
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuario.setText("Usuario");

        lblCClave.setFont(new java.awt.Font("Arial", 1, 12));
        lblCClave.setForeground(new java.awt.Color(0, 102, 204));
        lblCClave.setText("Cambiar de Clave");
        lblCClave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCClaveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                            .addComponent(lblCClave)
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblUsuario)
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addGap(23, 23, 23)
                .addComponent(lblCClave)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel1.setText("Actual Clave :");

        txtCActual.setFont(new java.awt.Font("Arial", 1, 14));
        txtCActual.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtNClave.setFont(new java.awt.Font("Arial", 1, 14));
        txtNClave.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtRClave.setFont(new java.awt.Font("Arial", 1, 14));
        txtRClave.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btn_CClave.setText("Actualizar Clave");
        btn_CClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CClaveActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel2.setText("Nueva Clave :");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel3.setText("Re - Clave :");

        btn_Cancelar.setText("Cancelar");
        btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PcambiarLayout = new javax.swing.GroupLayout(Pcambiar);
        Pcambiar.setLayout(PcambiarLayout);
        PcambiarLayout.setHorizontalGroup(
            PcambiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PcambiarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PcambiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PcambiarLayout.createSequentialGroup()
                        .addGroup(PcambiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PcambiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNClave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(txtCActual, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)))
                    .addGroup(PcambiarLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(PcambiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PcambiarLayout.createSequentialGroup()
                                .addComponent(btn_CClave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Cancelar))
                            .addGroup(PcambiarLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRClave, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)))))
                .addGap(20, 20, 20))
        );
        PcambiarLayout.setVerticalGroup(
            PcambiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PcambiarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PcambiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PcambiarLayout.createSequentialGroup()
                        .addComponent(txtCActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(PcambiarLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(PcambiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PcambiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PcambiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_CClave)
                    .addComponent(btn_Cancelar))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(Pcambiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Pcambiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 187, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        lblFecha.setFont(new java.awt.Font("Arial", 1, 14));
        lblFecha.setText("Fecha");

        lblHora.setFont(new java.awt.Font("Arial", 1, 14));
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHora.setText("Hora");

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cruzroja.png"))); // NOI18N
        jMenu1.setText("Hospital");

        jmi_Empleado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        jmi_Empleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/empleado.png"))); // NOI18N
        jmi_Empleado.setText("Empleado");
        jmi_Empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_EmpleadoActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_Empleado);

        jmt_Software.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        jmt_Software.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add_detalle_prod.png"))); // NOI18N
        jmt_Software.setText("Software");
        jmt_Software.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmt_SoftwareActionPerformed(evt);
            }
        });
        jMenu1.add(jmt_Software);

        jmi_Cargo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jmi_Cargo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add_detalle_prod.png"))); // NOI18N
        jmi_Cargo.setText("Cargo");
        jmi_Cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_CargoActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_Cargo);

        jmt_Are.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jmt_Are.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add_detalle_prod.png"))); // NOI18N
        jmt_Are.setText("Area");
        jmt_Are.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmt_AreActionPerformed(evt);
            }
        });
        jMenu1.add(jmt_Are);

        jmt_Departamento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        jmt_Departamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add_detalle_prod.png"))); // NOI18N
        jmt_Departamento.setText("Departamento");
        jmt_Departamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmt_DepartamentoActionPerformed(evt);
            }
        });
        jMenu1.add(jmt_Departamento);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Caracteristicas");

        jmi_Modelo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jmi_Modelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add_detalle_prod.png"))); // NOI18N
        jmi_Modelo.setText("Modelo");
        jmi_Modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_ModeloActionPerformed(evt);
            }
        });
        jMenu2.add(jmi_Modelo);

        jmt_Marca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        jmt_Marca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add_detalle_prod.png"))); // NOI18N
        jmt_Marca.setText("Marca");
        jmt_Marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmt_MarcaActionPerformed(evt);
            }
        });
        jMenu2.add(jmt_Marca);

        jmt_Tipo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK));
        jmt_Tipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add_detalle_prod.png"))); // NOI18N
        jmt_Tipo.setText("Tipo");
        jmt_Tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmt_TipoActionPerformed(evt);
            }
        });
        jMenu2.add(jmt_Tipo);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Ingreso de Equipo");

        jMenu3.setText("Computadora Estacionaria");

        jmi_Accesorios.setText("Accesorios");
        jmi_Accesorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_AccesoriosActionPerformed(evt);
            }
        });
        jMenu3.add(jmi_Accesorios);

        jmi_CPU.setText("CPU");
        jmi_CPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_CPUActionPerformed(evt);
            }
        });
        jMenu3.add(jmi_CPU);

        jmi_Monitor.setText("Monitor");
        jmi_Monitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_MonitorActionPerformed(evt);
            }
        });
        jMenu3.add(jmi_Monitor);

        jMenu5.setText("Armado de Computador");

        jmi_Componentes.setText("Por Componentes");
        jmi_Componentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_ComponentesActionPerformed(evt);
            }
        });
        jMenu5.add(jmi_Componentes);

        jmi_Partes.setText("Por Partes");
        jmi_Partes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_PartesActionPerformed(evt);
            }
        });
        jMenu5.add(jmi_Partes);

        jMenu3.add(jMenu5);

        jMenu4.add(jMenu3);

        jmi_Portatil.setText("Computadora Portatil");
        jmi_Portatil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_PortatilActionPerformed(evt);
            }
        });
        jMenu4.add(jmi_Portatil);

        jmi_Impresora.setText("Impresora");
        jmi_Impresora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_ImpresoraActionPerformed(evt);
            }
        });
        jMenu4.add(jmi_Impresora);

        jmi_Externo.setText("Equipo Externo");
        jmi_Externo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_ExternoActionPerformed(evt);
            }
        });
        jMenu4.add(jmi_Externo);

        jMenuBar1.add(jMenu4);

        jMenu6.setText("Proveedor");

        jmi_Proveedor.setText("Mantenedor");
        jmi_Proveedor.setActionCommand("");
        jmi_Proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_ProveedorActionPerformed(evt);
            }
        });
        jMenu6.add(jmi_Proveedor);

        jMenuBar1.add(jMenu6);

        jMenu8.setText("Usuario");

        jmi_Usuario.setText("Mantenerdor");
        jmi_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_UsuarioActionPerformed(evt);
            }
        });
        jMenu8.add(jmi_Usuario);

        jMenuBar1.add(jMenu8);

        jMenu7.setText("Ayuda");

        jMenuItem1.setText("Acerca de ...");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem1);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 388, Short.MAX_VALUE)
                        .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCPU5, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                            .addComponent(btnCPU6, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFecha)
                            .addComponent(lblHora))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCPU5)
                                .addGap(77, 77, 77)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(btnCPU6)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jmt_AreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmt_AreActionPerformed
// TODO add your handling code here:

    new frmArea(objUsuarioAdmin).setVisible(true);
    this.dispose();

}//GEN-LAST:event_jmt_AreActionPerformed

private void jmt_DepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmt_DepartamentoActionPerformed

    new frmDepartamento(objUsuarioAdmin).setVisible(true);
    this.dispose();

}//GEN-LAST:event_jmt_DepartamentoActionPerformed

    private void jmt_MarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmt_MarcaActionPerformed
        // TODO add your handling code here:
         new frmMarca(objUsuarioAdmin,true).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jmt_MarcaActionPerformed

    private void jmi_ModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_ModeloActionPerformed
        // TODO add your handling code here:
        new frmModelo(objUsuarioAdmin,true).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jmi_ModeloActionPerformed

    private void jmi_ImpresoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_ImpresoraActionPerformed
        // TODO add your handling code here:
  new frmImpresora(objUsuarioAdmin).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jmi_ImpresoraActionPerformed

private void jmi_EmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_EmpleadoActionPerformed
// TODO add your handling code here:
     new frmEmpleado(objUsuarioAdmin).setVisible(true);
    this.dispose();
}//GEN-LAST:event_jmi_EmpleadoActionPerformed

    private void jmi_CargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_CargoActionPerformed
        // TODO add your handling code here:
       new frmCargo(objUsuarioAdmin).setVisible(true);
    
    this.dispose();
    }//GEN-LAST:event_jmi_CargoActionPerformed

    private void jmi_ProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_ProveedorActionPerformed
        // TODO add your handling code here:
        new frmProveedor(objUsuarioAdmin).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jmi_ProveedorActionPerformed

    private void jmt_TipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmt_TipoActionPerformed
        // TODO add your handling code here:
          new frmTipo(objUsuarioAdmin,true).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmt_TipoActionPerformed

    private void jmi_ComponentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_ComponentesActionPerformed
        // TODO add your handling code here:
           new frmArmadoComputadoraPorComponentes(objUsuarioAdmin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmi_ComponentesActionPerformed

    private void jmi_AccesoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_AccesoriosActionPerformed
        // TODO add your handling code here:
           new frmIngresoAccesorios(objUsuarioAdmin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmi_AccesoriosActionPerformed

    private void jmi_PartesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_PartesActionPerformed
        // TODO add your handling code here:
         new frmArmadoComputadoraPoPartes(objUsuarioAdmin).setVisible(true);
        this.dispose();
 
    }//GEN-LAST:event_jmi_PartesActionPerformed

    private void jmi_CPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_CPUActionPerformed
        // TODO add your handling code here:
         new frmIngresoCPU(objUsuarioAdmin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmi_CPUActionPerformed

    private void jmi_MonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_MonitorActionPerformed
        // TODO add your handling code here:
         new frmIngresoMonitor(objUsuarioAdmin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmi_MonitorActionPerformed

    private void jmi_ExternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_ExternoActionPerformed
        // TODO add your handling code here:
          new frmEquipo(objUsuarioAdmin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmi_ExternoActionPerformed

    private void jmi_PortatilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_PortatilActionPerformed
        // TODO add your handling code here:
         new frmPortatil(objUsuarioAdmin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmi_PortatilActionPerformed

    private void jmt_SoftwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmt_SoftwareActionPerformed
        // TODO add your handling code here:
         new frmSoftware(objUsuarioAdmin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmt_SoftwareActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
        int i = JOptionPane.showConfirmDialog(this, "Esta seguro que desea Salir", "Confirmar Salida", JOptionPane.YES_NO_OPTION);         
        if (i == 0) {         
              new frmLogin().setVisible(true);
            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);          
        }    
    }//GEN-LAST:event_formWindowClosing

    private void btnCPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCPUActionPerformed
        // TODO add your handling code here:
        new frmModificarCPU(objUsuarioAdmin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCPUActionPerformed

    private void btnCPU1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCPU1ActionPerformed
        // TODO add your handling code here:
          new frmMantenimientoComputadoras(objUsuarioAdmin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCPU1ActionPerformed

    private void btnCPU2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCPU2ActionPerformed
        // TODO add your handling code here:
          new frmMantenimientoPortatil(objUsuarioAdmin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCPU2ActionPerformed

    private void btnCPU3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCPU3ActionPerformed
        // TODO add your handling code here:
          new frmMantenimientoImpresora(objUsuarioAdmin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCPU3ActionPerformed

    private void btnCPU4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCPU4ActionPerformed
        // TODO add your handling code here:
          new frmMantenimientoEquipo(objUsuarioAdmin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCPU4ActionPerformed

    private void btnCPU5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCPU5ActionPerformed
        // TODO add your handling code here:
          new frmOrdenCompra(objUsuarioAdmin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCPU5ActionPerformed

    private void btnCPU6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCPU6ActionPerformed
        // TODO add your handling code here:
        new frmComponentesInhabilitados(objUsuarioAdmin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCPU6ActionPerformed

    private void jmi_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_UsuarioActionPerformed
        // TODO add your handling code here:
        new frmUsuario(objUsuarioAdmin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmi_UsuarioActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
         new frmDatos(objUsuarioAdmin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

        private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
             int i = JOptionPane.showConfirmDialog(this, "Esta seguro que desea Salir", "Confirmar Salida", JOptionPane.YES_NO_OPTION);
            if (i == 0) {
              new frmLogin().setVisible(true);
                   this.dispose();
               
            }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarActionPerformed

          Panel.setVisible(true);
        Pcambiar.setVisible(false);
    }//GEN-LAST:event_btn_CancelarActionPerformed

    private void btn_CClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CClaveActionPerformed

        if(objUsuarioAdmin.getStr_clave().equals(txtCActual.getText()) )
        {
            if(txtNClave.getText().length()>5)
            {
            if(txtNClave.getText().equals(txtRClave.getText()))
            {
                
                    try {
                        objUsuarioAdmin.setStr_clave(txtNClave.getText());
                        if(objUsuarioCOM.actualizar(objUsuarioAdmin))
                        {
                             JOptionPane.showMessageDialog(this,"Se Cambio la Clave Correctamemte");
                            Panel.setVisible(true);
                             Pcambiar.setVisible(false);
                        }
                        else
                             JOptionPane.showMessageDialog(this,"Ocurrio un error");
                           
                    } catch (Exception ex) {}
                     
            }
            else
                 JOptionPane.showMessageDialog(this,"Su nueva Clave no coincide");
            }
            else
                JOptionPane.showMessageDialog(this,"Su clave debe ser de 6 digitos o mas");
                
        }
        else
             JOptionPane.showMessageDialog(this,"Clave Actual Incorrecta");
    }//GEN-LAST:event_btn_CClaveActionPerformed

    private void lblCClaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCClaveMouseClicked
        // TODO add your handling code here:
         Panel.setVisible(false);
        Pcambiar.setVisible(true);
    }//GEN-LAST:event_lblCClaveMouseClicked
   
        

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JPanel Pcambiar;
    private javax.swing.JButton btnCPU;
    private javax.swing.JButton btnCPU1;
    private javax.swing.JButton btnCPU2;
    private javax.swing.JButton btnCPU3;
    private javax.swing.JButton btnCPU4;
    private javax.swing.JButton btnCPU5;
    private javax.swing.JButton btnCPU6;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btn_CClave;
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JMenuItem jmi_Accesorios;
    private javax.swing.JMenuItem jmi_CPU;
    private javax.swing.JMenuItem jmi_Cargo;
    private javax.swing.JMenuItem jmi_Componentes;
    private javax.swing.JMenuItem jmi_Externo;
    private javax.swing.JMenuItem jmi_Impresora;
    private javax.swing.JMenuItem jmi_Modelo;
    private javax.swing.JMenuItem jmi_Monitor;
    private javax.swing.JMenuItem jmi_Partes;
    private javax.swing.JMenuItem jmi_Portatil;
    private javax.swing.JMenuItem jmi_Proveedor;
    private javax.swing.JMenuItem jmi_Usuario;
    private javax.swing.JMenuItem jmt_Are;
    private javax.swing.JMenuItem jmt_Departamento;
    private javax.swing.JMenuItem jmt_Marca;
    private javax.swing.JMenuItem jmt_Software;
    private javax.swing.JMenuItem jmt_Tipo;
    private javax.swing.JLabel lblCClave;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel panel;
    private javax.swing.JPasswordField txtCActual;
    private javax.swing.JPasswordField txtNClave;
    private javax.swing.JPasswordField txtRClave;
    // End of variables declaration//GEN-END:variables
}
