/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmArea.java
 *
 * Created on 06/09/2011, 05:59:13 PM
 */
package gui.Computador;
import gui.frmMantenimientoComputadoras;
import com.*;
import entidades.*;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import modelo.*;
/**
 *
 * @author Toditos
 */
public class frmModificarAccesorios extends javax.swing.JFrame {
    
    private Usuario objUsuarioAdmin = new Usuario();
    private List<Accesorios> listAccesoriosOperativo = new ArrayList<Accesorios>();
    private List<Accesorios> listAccesoriosNoOperativo = new ArrayList<Accesorios>();
    private AccesoriosCOM objAccesoriosCOM = new AccesoriosCOM();
    HistorialComponenteCOM objHistorialComponenteCOM = new HistorialComponenteCOM();
    
    ComponenteCOM objComponenteCOM = new ComponenteCOM();

    


           
       private Computador objComputador= new Computador();
       
      private ModeloAccesorios modeloTablaAccesoriosActual = new ModeloAccesorios();
      private ModeloAccesorios modeloTablaAccesoriosNuevo = new ModeloAccesorios();


     

   
            private DefaultComboBoxModel ComboComponenteAcc = new DefaultComboBoxModel();
    public frmModificarAccesorios(Usuario usuario,Computador objComputador) {
        initComponents();
           this.setIconImage (new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage()); 
         setLocationRelativeTo(null);
         this.objComputador=objComputador;
        this.objUsuarioAdmin = usuario;
         tablaDetalleAccActual.setModel(modeloTablaAccesoriosActual);
          tablaDetalleAccNuevo.setModel(modeloTablaAccesoriosNuevo);
      cb_ListarComponenteAcc.setModel(ComboComponenteAcc);

         tablaDetalleAccActual.getColumnModel().getColumn(0).setMaxWidth(100);
           tablaDetalleAccActual.getColumnModel().getColumn(0).setMinWidth(100);
           tablaDetalleAccNuevo.getColumnModel().getColumn(0).setMaxWidth(100);
           tablaDetalleAccNuevo.getColumnModel().getColumn(0).setMinWidth(100);
            tablaDetalleAccActual.getColumnModel().getColumn(1).setMaxWidth(100);
            tablaDetalleAccActual.getColumnModel().getColumn(1).setMinWidth(100);
             tablaDetalleAccNuevo.getColumnModel().getColumn(1).setMaxWidth(100);
            tablaDetalleAccNuevo.getColumnModel().getColumn(1).setMinWidth(100);

LlenarCampos();
listarComboAccesorios();

    }
     
          public void listarComboAccesorios()
    {
        ComboComponenteAcc.removeAllElements();
        ComboComponenteAcc.addElement("(Seleccione una Opcion)");
         try {
            List<Accesorios> listAccesorios = objAccesoriosCOM.listarTodosOrdenado(4);
            if(listAccesorios!=null)
            {
                for(Accesorios a : listAccesorios)
                {
                    ComboComponenteAcc.addElement(a);
                }
            }
        } catch (Exception e) {
           
        }
  
    }
          
    
    public void LlenarCampos()
    {
         lblIdComputador.setText(objComputador.getStr_id_computador());
        
        try {    
           
             List<Accesorios> listAccesorios = objAccesoriosCOM.listarAccesoriosXComputador(objComputador.getStr_id_computador());
              if(listAccesorios!=null)
             for(Accesorios accesorios : listAccesorios)
                {
           
                         modeloTablaAccesoriosActual.insertar(accesorios);
     
                }
             modeloTablaAccesoriosActual.fireTableDataChanged();
            
            
        } catch (Exception ex) {
            Logger.getLogger(frmModificarAccesorios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

           
     

     
    
         
 
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblIdComputador = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaDetalleAccActual = new javax.swing.JTable();
        btnQuitarCPU1 = new javax.swing.JButton();
        chkEstado = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        lblContador = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        btnAgregarAc1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaDetalleAccNuevo = new javax.swing.JTable();
        cb_ListarComponenteAcc = new javax.swing.JComboBox();
        btnQuitarCPU3 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulario de Modificacion del CPU");
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 51, 0));

        jPanel5.setBackground(new java.awt.Color(153, 51, 0));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Modificacion de Accesorios");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/computador.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(jLabel11))
                .addContainerGap())
        );

        jLabel23.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel23.setText("Nombre de Computador:");

        lblIdComputador.setFont(new java.awt.Font("Arial", 1, 14));
        lblIdComputador.setText("Autogenerado");

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/orden.png"))); // NOI18N
        btnModificar.setText("Modifcar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Actuales Accesorios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        tablaDetalleAccActual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaDetalleAccActual.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane4.setViewportView(tablaDetalleAccActual);

        btnQuitarCPU1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btnQuitarCPU1.setToolTipText("Quitar Accesorios");
        btnQuitarCPU1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarCPU1ActionPerformed(evt);
            }
        });

        chkEstado.setFont(new java.awt.Font("Arial", 1, 12));
        chkEstado.setSelected(true);
        chkEstado.setText("Componente Operativo");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11));
        jLabel2.setText("Compoentes Retirados :");

        lblContador.setFont(new java.awt.Font("Arial", 1, 11));
        lblContador.setText("0");

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editclear.png"))); // NOI18N
        btnLimpiar.setText("Restaurar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(btnQuitarCPU1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chkEstado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(1, 1, 1)
                                .addComponent(lblContador, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)))
                        .addComponent(btnLimpiar))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnQuitarCPU1)
                            .addComponent(chkEstado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblContador))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnLimpiar)
                        .addGap(27, 27, 27))))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nuevos Accesorios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        btnAgregarAc1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add_detalle_prod.png"))); // NOI18N
        btnAgregarAc1.setToolTipText("Agregar Accesorios");
        btnAgregarAc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAc1ActionPerformed(evt);
            }
        });

        tablaDetalleAccNuevo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaDetalleAccNuevo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane5.setViewportView(tablaDetalleAccNuevo);

        btnQuitarCPU3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete_detalle_prod.png"))); // NOI18N
        btnQuitarCPU3.setToolTipText("Quitar Accesorios");
        btnQuitarCPU3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarCPU3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(btnAgregarAc1)
                        .addGap(3, 3, 3)
                        .addComponent(btnQuitarCPU3))
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                        .addComponent(cb_ListarComponenteAcc, javax.swing.GroupLayout.Alignment.LEADING, 0, 431, Short.MAX_VALUE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(cb_ListarComponenteAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addGap(7, 7, 7)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnQuitarCPU3)
                    .addComponent(btnAgregarAc1)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblIdComputador)
                .addGap(208, 208, 208))
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(190, Short.MAX_VALUE)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(lblIdComputador))
                .addGap(10, 10, 10)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificar)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
// TODO add your handling code here:

   new frmMostrarComputadora(objUsuarioAdmin,objComputador).setVisible(true);
   



}//GEN-LAST:event_formWindowClosed

    private void btnQuitarCPU1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarCPU1ActionPerformed
        // TODO add your handling code here:
          if(tablaDetalleAccActual.getSelectedRow()>-1)
        {
            Accesorios objAccesorios = new Accesorios();
            
            objAccesorios = modeloTablaAccesoriosActual.listar().get(tablaDetalleAccActual.getSelectedRow());
            if(chkEstado.isSelected())
            listAccesoriosOperativo.add(objAccesorios);
            else
            listAccesoriosNoOperativo.add(objAccesorios);
            
            int c=Integer.valueOf(lblContador.getText());
            c++;
            modeloTablaAccesoriosActual.removerItemDetalle(tablaDetalleAccActual.getSelectedRow());
            modeloTablaAccesoriosActual.fireTableDataChanged();
            lblContador.setText(String.valueOf(c));
            chkEstado.setSelected(true);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Seleccione Una Fila");
        }
    }//GEN-LAST:event_btnQuitarCPU1ActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        LlenarCampos();
        lblContador.setText("0");
        listAccesoriosNoOperativo.clear();
        listAccesoriosOperativo.clear();
        chkEstado.setSelected(true);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
       try {

            if(modeloTablaAccesoriosNuevo!=null)
            for(Accesorios accesorios: modeloTablaAccesoriosNuevo.listar())
               {                   
                
                objAccesoriosCOM.insertarComputadorAccesorios( lblIdComputador.getText(),accesorios.getStr_id_accesorios());
                  objComponenteCOM.actualizarEstado(accesorios.getObjComponente().getStr_id_componente(),2);
                    objHistorialComponenteCOM.insertar(accesorios.getObjComponente().getStr_id_componente(),"Se Inserto en el computador "+objComputador.getStr_id_computador());    
               }
               
             if(listAccesoriosNoOperativo!=null)
            for(Accesorios accesorios:listAccesoriosNoOperativo)
            {
                objAccesoriosCOM.eliminarComputadorComponete(lblIdComputador.getText(),accesorios.getStr_id_accesorios());
                     objComponenteCOM.actualizarEstado(accesorios.getObjComponente().getStr_id_componente(),3);
                     objHistorialComponenteCOM.insertar(accesorios.getObjComponente().getStr_id_componente(),"Se Inhabilito en el computador "+objComputador.getStr_id_computador());
       
            }

                if(listAccesoriosOperativo!=null)
            for(Accesorios accesorios:listAccesoriosOperativo)
            {
                if(objAccesoriosCOM.eliminarComputadorComponete(lblIdComputador.getText(), accesorios.getStr_id_accesorios()))
                     objComponenteCOM.actualizarEstado(accesorios.getObjComponente().getStr_id_componente(),4);
                  objHistorialComponenteCOM.insertar(accesorios.getObjComponente().getStr_id_componente(),"Se Retiro en el computador "+objComputador.getStr_id_computador());
       
            }
              
                
                
               
        
                
                
                
                
                
                
             } catch (Exception ex) {
                Logger.getLogger(frmModificarAccesorios.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();

    }//GEN-LAST:event_btnModificarActionPerformed

        private void btnAgregarAc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAc1ActionPerformed
        // TODO add your handling code here:
             if(cb_ListarComponenteAcc.getSelectedIndex()!=0  )
            {
   
                    if(!modeloTablaAccesoriosNuevo.insertar(((Accesorios)cb_ListarComponenteAcc.getSelectedItem())))
                    JOptionPane.showMessageDialog(this,"Numero de Patrimonial o Serie Duplicado");
                    else
                    modeloTablaAccesoriosNuevo.fireTableDataChanged();
                    cb_ListarComponenteAcc.setSelectedIndex(0);
            }
            else
             JOptionPane.showMessageDialog(this,"Selecione un Accesorio");

    }//GEN-LAST:event_btnAgregarAc1ActionPerformed

    private void btnQuitarCPU3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarCPU3ActionPerformed
        // TODO add your handling code here:
        if(tablaDetalleAccNuevo.getSelectedRow()>-1)
        {
            

            modeloTablaAccesoriosNuevo.removerItemDetalle(tablaDetalleAccNuevo.getSelectedRow());
            modeloTablaAccesoriosNuevo.fireTableDataChanged();

        }
        else
        {
            JOptionPane.showMessageDialog(this, "Seleccione Una Fila");
        }
    }//GEN-LAST:event_btnQuitarCPU3ActionPerformed

     
    
    
  
    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarAc1;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnQuitarCPU1;
    private javax.swing.JButton btnQuitarCPU3;
    private javax.swing.JComboBox cb_ListarComponenteAcc;
    private javax.swing.JCheckBox chkEstado;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblContador;
    private javax.swing.JLabel lblIdComputador;
    private javax.swing.JTable tablaDetalleAccActual;
    private javax.swing.JTable tablaDetalleAccNuevo;
    // End of variables declaration//GEN-END:variables
}
